### ISSUE TITLE
Latest version crashes on launch

### ISSUE THREAD

**Issue by neurovertex** [shrewdlogarithm/steamtray#3]
I had steamtray installed, updated it to 0.113 yesterday, and after the update it wouldn't start, showing an error after the splash screen.

```
TypeError: Cannot read property 'length' of null
    at shortcutparse (file:///C:/Users/Neurovertex/AppData/Local/Temp/nw15956_19740/mods/steamload.js:321:34)
    at Object.my.loadVDFs (file:///C:/Users/Neurovertex/AppData/Local/Temp/nw15956_19740/mods/steamload.js:162:32)
    at doload (file:///C:/Users/Neurovertex/AppData/Local/Temp/nw15956_19740/mods/steamload.js:81:20)
    at Object.func (file:///C:/Users/Neurovertex/AppData/Local/Temp/nw15956_19740/mods/steamload.js:88:13)
    at Object.my.execute (file:///C:/Users/Neurovertex/AppData/Local/Temp/nw15956_19740/libs/handlers.js:34:36)
    at file:///C:/Users/Neurovertex/AppData/Local/Temp/nw15956_19740/nw.html:21:42
    at checkloaded (file:///C:/Users/Neurovertex/AppData/Local/Temp/nw15956_19740/libs/modmanager.js:31:13)
    at file:///C:/Users/Neurovertex/AppData/Local/Temp/nw15956_19740/libs/modmanager.js:28:17
```

**Comment by shrewdlogarithm** [comment]
Ah - have you perhaps removed all your non-Steam shortcuts?  That would explain the error...

I've pushed a fix but that error will stop the automatic update from working I suspect - to get around that create a shortcut to anything within Steam and then run steamtray - that should suppress the error, the update will then download, restart Steamtray and you can then delete the shortcut and it shouldn't crash again

Sorry about that!

**Comment by neurovertex** [comment]
Maybe I did remove a shortcut, I can't recall for sure. I updated it manually, and the issue is indeed fixed. Thanks ^^
